create table if not exists public.woocommerce_order_status_reason (
  code          varchar(64) primary key,
  target_status varchar(32) not null check (target_status in ('cancelled', 'refunded')),
  label         varchar(255) not null,
  sort_order    integer not null default 0,
  is_active     boolean not null default true
);

create table if not exists public.woocommerce_order_status_history (
  id                    bigint generated by default as identity primary key,
  woocommerce_order_id  bigint not null references public.woocommerce_order(woocommerce_order_id) on delete cascade,
  from_status           varchar(32),
  to_status             varchar(32) not null,
  reason_code           varchar(64) references public.woocommerce_order_status_reason(code) on delete restrict,
  note                  varchar(1000),
  source                varchar(32) not null,
  changed_by            bigint references public.account(id) on delete set null,
  created_at            timestamptz not null default now(),
  check (to_status in ('pending', 'processing', 'on-hold', 'completed', 'cancelled', 'refunded', 'failed', 'draft')),
  check (source in ('warehouse', 'woocommerce', 'system'))
);

create index if not exists ix_woocommerce_order_status_history_order_created
  on public.woocommerce_order_status_history (woocommerce_order_id, created_at desc);

insert into public.woocommerce_order_status_reason (code, target_status, label, sort_order)
values
  ('cancel_customer_request', 'cancelled', 'Khách hàng yêu cầu hủy đơn', 10),
  ('cancel_out_of_stock', 'cancelled', 'Hết hàng hoặc không đủ tồn kho', 20),
  ('cancel_invalid_address', 'cancelled', 'Thông tin giao hàng không hợp lệ', 30),
  ('cancel_duplicate_order', 'cancelled', 'Đơn hàng bị trùng', 40),
  ('cancel_unreachable_customer', 'cancelled', 'Không liên hệ được với khách hàng', 50),
  ('cancel_price_error', 'cancelled', 'Sai giá hoặc sai thông tin sản phẩm', 60),
  ('cancel_other', 'cancelled', 'Lý do khác', 99),
  ('refund_customer_request', 'refunded', 'Khách hàng yêu cầu hoàn tiền', 10),
  ('refund_wrong_item', 'refunded', 'Giao sai sản phẩm', 20),
  ('refund_damaged_item', 'refunded', 'Sản phẩm bị hư hỏng', 30),
  ('refund_missing_item', 'refunded', 'Thiếu sản phẩm trong đơn', 40),
  ('refund_payment_issue', 'refunded', 'Lỗi thanh toán hoặc thanh toán trùng', 50),
  ('refund_other', 'refunded', 'Lý do khác', 99)
on conflict (code) do nothing;

insert into public.app_schema_version (id, version, applied_at)
values (1, '20260818093833', now())
on conflict (id) do update
set version = excluded.version,
    applied_at = excluded.applied_at;
